### ISSUE TITLE
my data is stuck

### ISSUE THREAD

**Issue by jehiah** [jayridge/phonebyjay#11]
All my information is on this phone and it's stuck. I can't get it out. I tried washing it but that didn't help. Please send me my information soon. I really need it for my boss by monday

**Comment by jayridge** [comment]
@jehiah I will happily retrieve your data. Please send $100 so I can get started.

**Comment by jehiah** [comment]
please send account number. I will happily wire out the funds.

**Comment by jlintz** [comment]
@jehiah please post credit card number in issue for sake of open data
